Repository operator-framework/operator-sdk-samples, pull requests merged in 2019-04, with the labels that each got.

#58 memcached-operator: bump to operator-sdk v0.6.0
  memcached-operator/Gopkg.lock
  memcached-operator/Gopkg.toml
  memcached-operator/build/Dockerfile
  memcached-operator/build/bin/entrypoint
  memcached-operator/build/bin/user_setup
  memcached-operator/build/test-framework/Dockerfile
  memcached-operator/build/test-framework/go-test.sh
  memcached-operator/cmd/manager/main.go
  memcached-operator/deploy/crds/cache_v1alpha1_memcached_crd.yaml
  memcached-operator/deploy/operator.yaml
  memcached-operator/deploy/role.yaml
  memcached-operator/deploy/test-pod.yaml
  memcached-operator/pkg/apis/cache/v1alpha1/memcached_types.go
  memcached-operator/pkg/apis/cache/v1alpha1/zz_generated.openapi.go
Labels: size/XL

#60 Add 2 CSV's and regenerate k8s/openapi code
  deploy/olm-catalog/operator-sdk-samples/0.6.0/operator-sdk-samples.v0.6.0.clusterserviceversion.yaml
  memcached-operator/deploy/crds/cache_v1alpha1_memcached_crd.yaml
  memcached-operator/deploy/olm-catalog/memcached-operator/0.5.0/memcached-operator.v0.5.0.clusterserviceversion.yaml
  memcached-operator/deploy/olm-catalog/memcached-operator/0.6.0/memcached-operator.v0.6.0.clusterserviceversion.yaml
  memcached-operator/pkg/apis/cache/v1alpha1/zz_generated.deepcopy.go
Labels: size/L

#61 remove empty deploy dir
  deploy/olm-catalog/operator-sdk-samples/0.6.0/operator-sdk-samples.v0.6.0.clusterserviceversion.yaml
Labels: lgtm, size/XS
