Repository operator-framework/operator-sdk-samples, pull requests merged in 2019-12, with the labels that each got.

#90 Go sample upgrade to use SDK 0.12
  memcached-operator/README.md
  memcached-operator/cmd/manager/main.go
  memcached-operator/deploy/crds/cache.example.com_memcacheds_crd.yaml
  memcached-operator/deploy/olm-catalog/memcached-operator/0.12.0/memcached-operator.v0.12.0.clusterserviceversion.yaml
  memcached-operator/deploy/olm-catalog/memcached-operator/memcached-operator.package.yaml
  memcached-operator/go.mod
  memcached-operator/go.sum
  memcached-operator/pkg/apis/cache/v1alpha1/memcached_types.go
  memcached-operator/pkg/apis/cache/v1alpha1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/XL

#97 Add go dir and move sample
  .gitignore
  go/memcached-operator/.gitignore
  go/memcached-operator/Makefile
  go/memcached-operator/README.md
  go/memcached-operator/build/Dockerfile
  go/memcached-operator/build/bin/entrypoint
  go/memcached-operator/build/bin/user_setup
  go/memcached-operator/cmd/manager/main.go
  go/memcached-operator/deploy/crds/cache.example.com_memcacheds_crd.yaml
  go/memcached-operator/deploy/crds/cache.example.com_v1alpha1_memcached_cr.yaml
  go/memcached-operator/deploy/olm-catalog/memcached-operator/0.10.0/memcached-operator.v0.10.0.clusterserviceversion.yaml
  go/memcached-operator/deploy/olm-catalog/memcached-operator/0.11.0/memcached-operator.v0.11.0.clusterserviceversion.yaml
  go/memcached-operator/deploy/olm-catalog/memcached-operator/0.12.0/memcached-operator.v0.12.0.clusterserviceversion.yaml
  go/memcached-operator/deploy/olm-catalog/memcached-operator/0.5.0/memcached-operator.v0.5.0.clusterserviceversion.yaml
  go/memcached-operator/deploy/olm-catalog/memcached-operator/0.6.0/memcached-operator.v0.6.0.clusterserviceversion.yaml
  go/memcached-operator/deploy/olm-catalog/memcached-operator/memcached-operator.package.yaml
  go/memcached-operator/deploy/operator.yaml
  go/memcached-operator/deploy/role.yaml
  go/memcached-operator/deploy/role_binding.yaml
  go/memcached-operator/deploy/service_account.yaml
  go/memcached-operator/go.mod
  go/memcached-operator/go.sum
  go/memcached-operator/pkg/apis/addtoscheme_cache_v1alpha1.go
  go/memcached-operator/pkg/apis/apis.go
  go/memcached-operator/pkg/apis/cache/group.go
  go/memcached-operator/pkg/apis/cache/v1alpha1/doc.go
  go/memcached-operator/pkg/apis/cache/v1alpha1/memcached_types.go
  go/memcached-operator/pkg/apis/cache/v1alpha1/register.go
  go/memcached-operator/pkg/apis/cache/v1alpha1/zz_generated.deepcopy.go
  go/memcached-operator/pkg/apis/cache/v1alpha1/zz_generated.openapi.go
  go/memcached-operator/pkg/controller/add_memcached.go
  go/memcached-operator/pkg/controller/controller.go
  go/memcached-operator/pkg/controller/memcached/memcached_controller.go
  go/memcached-operator/pkg/controller/memcached/memcached_controller_test.go
  go/memcached-operator/test/e2e/main_test.go
  go/memcached-operator/test/e2e/memcached_test.go
  go/memcached-operator/version/version.go
Labels: approved, lgtm, size/M

#99 doc: add go readme in the samples
  go/README.md
  go/memcached-operator/README.md
Labels: size/XS

#101 Update the words
  go/memcached-operator/Makefile
Labels: lgtm, size/XS

#103 update README to address minor issues
  ansible/memcached-operator/README.md
  go/memcached-operator/README.md
  helm/memcached-operator/README.md
Labels: size/S

#104 typo error
  ansible/memcached-operator/Makefile
  helm/memcached-operator/Makefile
Labels: size/S
