Repository operator-framework/operator-sdk-samples, pull requests merged in 2019-10, with the labels that each got.

#73 Update README to add test related target
  memcached-operator/README.md
Labels: size/XS

#74 upgrade ansible memcached operator project to use version v0.10.0 of sdk
  .gitignore
  ansible/memcached-operator/.gitgnore
  ansible/memcached-operator/.travis.yml
  ansible/memcached-operator/Makefile
  ansible/memcached-operator/README.md
  ansible/memcached-operator/build/Dockerfile
  ansible/memcached-operator/build/test-framework/Dockerfile
  ansible/memcached-operator/build/test-framework/ansible-test.sh
  ansible/memcached-operator/deploy/crds/cache_v1alpha1_memcached_cr.yaml
  ansible/memcached-operator/deploy/crds/cache_v1alpha1_memcached_crd.yaml
  ansible/memcached-operator/deploy/operator.yaml
  ansible/memcached-operator/deploy/role.yaml
  ansible/memcached-operator/molecule/default/asserts.yml
  ansible/memcached-operator/molecule/default/molecule.yml
  ansible/memcached-operator/molecule/default/playbook.yml
  ansible/memcached-operator/molecule/default/prepare.yml
  ansible/memcached-operator/molecule/test-cluster/molecule.yml
  ansible/memcached-operator/molecule/test-cluster/playbook.yml
  ansible/memcached-operator/molecule/test-local/molecule.yml
  ansible/memcached-operator/molecule/test-local/playbook.yml
  ansible/memcached-operator/molecule/test-local/prepare.yml
  ansible/memcached-operator/roles/Memcached/meta/main.yml
  ansible/memcached-operator/roles/Memcached/tasks/main.yml
  ansible/memcached-operator/watches.yaml
  memcached-operator/README.md
Labels: size/XL

#76 Adjust Travisfile to install required jmespath dependency per operator-sdk #2023.
  ansible/memcached-operator/.travis.yml
Labels: lgtm, size/XS

#75 cleanup the e2e help text and help target
  memcached-operator/Makefile
  memcached-operator/README.md
Labels: approved, lgtm, size/M

#78 Upgrade helm sample to 0.11.0 version of SDK
  .gitignore
  helm/memcached-operator/Makefile
  helm/memcached-operator/README.md
  helm/memcached-operator/build/Dockerfile
  helm/memcached-operator/deploy/crds/cache.example.com_v1alpha1_memcached_cr.yaml
  helm/memcached-operator/deploy/crds/cache.example.com_v1alpha1_memcached_crd.yaml
  helm/memcached-operator/deploy/crds/cache_v1alpha1_memcached_cr.yaml
  helm/memcached-operator/deploy/operator.yaml
  helm/memcached-operator/deploy/role.yaml
  helm/memcached-operator/helm-charts/memcached/.helmignore
  helm/memcached-operator/helm-charts/memcached/Chart.yaml
  helm/memcached-operator/helm-charts/memcached/README.md
  helm/memcached-operator/helm-charts/memcached/templates/NOTES.txt
  helm/memcached-operator/helm-charts/memcached/templates/_helpers.tpl
  helm/memcached-operator/helm-charts/memcached/templates/deployment.yaml
  helm/memcached-operator/helm-charts/memcached/templates/pdb.yaml
  helm/memcached-operator/helm-charts/memcached/templates/service.yaml
  helm/memcached-operator/helm-charts/memcached/templates/statefulset.yaml
  helm/memcached-operator/helm-charts/memcached/templates/svc.yaml
  helm/memcached-operator/helm-charts/memcached/templates/tests/test-connection.yaml
  helm/memcached-operator/helm-charts/memcached/values.yaml
Labels: size/XL

#80 upgrade to use sdk 11
  ansible/memcached-operator/build/Dockerfile
  ansible/memcached-operator/build/test-framework/Dockerfile
Labels: size/XS

#83 Updated README for memcached-operator.
  memcached-operator/README.md
Labels: lgtm, size/S
