Repository operator-framework/operator-sdk-samples, pull requests merged in 2020-02, with the labels that each got.

#102 [Makefile improvements] - Fix local test which is missing `"` to close the string param and add || true to create namespace step to avoid the output `Error 1 (ignored)`
  go/memcached-operator/Makefile
Labels: lgtm, size/XS

#105 Update sample projects to use operator-sdk 0.13
  ansible/memcached-operator/README.md
  ansible/memcached-operator/build/Dockerfile
  ansible/memcached-operator/deploy/crds/cache.example.com_memcacheds_crd.yaml
  ansible/memcached-operator/deploy/role.yaml
  ansible/memcached-operator/roles/Memcached/tests/inventory
  go/memcached-operator/README.md
  go/memcached-operator/deploy/crds/cache.example.com_memcacheds_crd.yaml
  go/memcached-operator/deploy/olm-catalog/memcached-operator/0.13.0/memcached-operator.v0.13.0.clusterserviceversion.yaml
  go/memcached-operator/deploy/olm-catalog/memcached-operator/memcached-operator.package.yaml
  go/memcached-operator/deploy/operator.yaml
  go/memcached-operator/deploy/role.yaml
  go/memcached-operator/go.mod
  go/memcached-operator/go.sum
  helm/memcached-operator/README.md
  helm/memcached-operator/build/Dockerfile
  helm/memcached-operator/deploy/operator.yaml
  helm/memcached-operator/deploy/role.yaml
Labels: size/XL

#106 Update GO operator to SDK 0.14
  go/memcached-operator/cmd/manager/main.go
  go/memcached-operator/deploy/crds/cache.example.com_memcacheds_crd.yaml
  go/memcached-operator/deploy/olm-catalog/memcached-operator/0.14.0/memcached-operator.v0.14.0.clusterserviceversion.yaml
  go/memcached-operator/deploy/olm-catalog/memcached-operator/memcached-operator.package.yaml
  go/memcached-operator/go.mod
  go/memcached-operator/go.sum
Labels: lgtm, size/XL

#107 Update Ansible to SDK 0.14.1
  ansible/memcached-operator/build/Dockerfile
  ansible/memcached-operator/molecule/default/asserts.yml
  ansible/memcached-operator/molecule/test-cluster/playbook.yml
  ansible/memcached-operator/molecule/test-local/playbook.yml
  ansible/memcached-operator/roles/Memcached/meta/main.yml
Labels: lgtm, size/S

#110 Helm upgrade for 0.14.1
  helm/memcached-operator/build/Dockerfile
  helm/memcached-operator/deploy/crds/cache.example.com_memcacheds_crd.yaml
  helm/memcached-operator/deploy/role.yaml
  helm/memcached-operator/watches.yaml
Labels: size/S

#109 Update Go and Ansible operators to SDK 0.15.2
  ansible/memcached-operator/build/Dockerfile
  go/memcached-operator/build/bin/entrypoint
  go/memcached-operator/build/bin/user_setup
  go/memcached-operator/deploy/olm-catalog/memcached-operator/0.15.2/memcached-operator.v0.15.2.clusterserviceversion.yaml
  go/memcached-operator/deploy/olm-catalog/memcached-operator/memcached-operator.package.yaml
  go/memcached-operator/deploy/operator.yaml
  go/memcached-operator/go.mod
  go/memcached-operator/go.sum
Labels: lgtm, size/L

#112 add extra info in helm README
  helm/memcached-operator/README.md
Labels: size/XS

#111 Update Helm operator to SDK 0.15.2
  helm/memcached-operator/build/Dockerfile
  helm/memcached-operator/deploy/crds/cache.example.com_v1alpha1_memcached_cr.yaml
  helm/memcached-operator/helm-charts/memcached/Chart.yaml
  helm/memcached-operator/helm-charts/memcached/README.md
  helm/memcached-operator/helm-charts/memcached/templates/NOTES.txt
  helm/memcached-operator/helm-charts/memcached/templates/_helpers.tpl
  helm/memcached-operator/helm-charts/memcached/templates/pdb.yaml
  helm/memcached-operator/helm-charts/memcached/templates/statefulset.yaml
  helm/memcached-operator/helm-charts/memcached/templates/svc.yaml
  helm/memcached-operator/helm-charts/memcached/values.yaml
Labels: size/M

#114 update project to use relative paths in the watches
  ansible/memcached-operator/watches.yaml
Labels: lgtm, size/XS
